services:
  - type: web
    name: crossdrop
    env: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_VERSION
        value: 20
      - key: HOST
        value: 0.0.0.0
